GRANT EXECUTE ON SCHEMA:: [dbo] TO [db_apiETL]
GO
GRANT SELECT ON SCHEMA:: [dbo] TO [db_apiETL]
GO
GRANT EXECUTE ON SCHEMA:: [dbo] TO [db_DataUpload]
GO
GRANT SELECT ON SCHEMA:: [dbo] TO [db_DataUpload]
GO
